const $=s=>document.querySelector(s),screens=["home","tracker","summary"];let stream=null,facing="environment",tracking=false,rally=false,sessionStart=0,rallyStart=0,timer=null,mediaRecorder=null,chunks=[],videoBlob=null,visionTimer=null,lastPos=null,data={rallies:[],shots:0,movement:[]};
function show(id){screens.forEach(x=>$("#"+x).classList.toggle("active",x===id));scrollTo(0,0)}function fmt(ms,d=false){let s=Math.max(0,ms)/1000,m=Math.floor(s/60),r=s%60;return`${m}:${d?r.toFixed(1).padStart(4,"0"):Math.floor(r).toString().padStart(2,"0")}`}
async function startCamera(){stopCamera();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30}},audio:true});camera.srcObject=stream;cameraFallback.style.display="none";visionStatus.textContent="Camera + microphone ready"}catch(e){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing}},audio:false});camera.srcObject=stream;cameraFallback.style.display="none";visionStatus.textContent="Camera ready · no audio"}catch(x){cameraFallback.style.display="grid";visionStatus.textContent="Camera unavailable"}}}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function bestMime(){let types=["video/mp4;codecs=h264,aac","video/mp4","video/webm;codecs=vp9,opus","video/webm;codecs=vp8,opus","video/webm"];return types.find(t=>window.MediaRecorder&&MediaRecorder.isTypeSupported(t))||""}
function startRecording(){chunks=[];videoBlob=null;if(!stream||!window.MediaRecorder)return;try{let mime=bestMime();mediaRecorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);mediaRecorder.ondataavailable=e=>{if(e.data&&e.data.size)chunks.push(e.data)};mediaRecorder.onstop=()=>{videoBlob=new Blob(chunks,{type:mediaRecorder.mimeType||"video/webm"});savedVideo.src=URL.createObjectURL(videoBlob);videoCard.classList.remove("hidden");videoNote.textContent=`${(videoBlob.size/1048576).toFixed(1)} MB · kept on this device until you leave/reload`;saveVideoBtn.textContent="Save video"};mediaRecorder.start(1000)}catch(e){console.warn("Recording unavailable",e)}}
function stopRecording(){return new Promise(resolve=>{if(mediaRecorder&&mediaRecorder.state!=="inactive"){mediaRecorder.addEventListener("stop",resolve,{once:true});mediaRecorder.stop()}else resolve()})}
function saveVideo(){if(!videoBlob)return;let ext=videoBlob.type.includes("mp4")?"mp4":"webm",name=`ShuttleVision-${new Date().toISOString().replace(/[:.]/g,"-")}.${ext}`,url=URL.createObjectURL(videoBlob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);saveVideoBtn.textContent="Video saved ✓"}
function update(){rallies.textContent=data.rallies.length;shots.textContent=data.shots;movement.textContent=data.movement.length}
function setUI(){sessionBtn.textContent=tracking?"End & Save Session":"Start & Record";shotBtn.disabled=!tracking||!rally;rallyBtn.disabled=!tracking;rallyBtn.textContent=rally?"End rally":"Start rally";statusPill.textContent=tracking?"TRACKING":"READY";statusPill.className="status "+(tracking?"live":"idle");rallyLive.classList.toggle("hidden",!rally);recPill.classList.toggle("hidden",!tracking)}
function beginSession(){if(!stream)return alert("Camera is not ready yet.");tracking=true;sessionStart=Date.now();data={rallies:[],shots:0,currentShots:0,movement:[]};lastPos=null;startRecording();startVision();update();setUI();timer=setInterval(()=>{if(rally)liveTime.textContent=fmt(Date.now()-rallyStart,true);recTime.textContent=fmt(Date.now()-sessionStart)},100)}
function toggleRally(){if(!tracking)return;if(!rally){rally=true;rallyStart=Date.now();data.currentShots=0}else endRally();update();setUI()}function endRally(){if(!rally)return;data.rallies.push({shots:data.currentShots||0,duration:Date.now()-rallyStart});rally=false;data.currentShots=0}function addShot(){if(!rally)return;data.currentShots++;data.shots++;navigator.vibrate?.(18);update()}
function startVision(){clearInterval(visionTimer);if(!visionToggle.checked)return;visionStatus.textContent="Tracking movement";visionTimer=setInterval(sampleMovement,450)}function stopVision(){clearInterval(visionTimer);visionTimer=null;visionStatus.textContent="Vision paused"}
function sampleMovement(){if(!tracking||!visionToggle.checked)return;/* V2 browser-safe motion proxy: estimates activity from frame luminance centroid. A pose model can replace this module without changing the session pipeline. */let c=visionCanvas,ctx=c.getContext("2d",{willReadFrequently:true}),w=96,h=128;c.width=w;c.height=h;try{ctx.drawImage(camera,0,0,w,h);let p=ctx.getImageData(0,0,w,h).data,sx=0,sy=0,n=0;for(let y=8;y<h;y+=4)for(let x=4;x<w;x+=4){let i=(y*w+x)*4,l=(p[i]+p[i+1]+p[i+2])/3;if(l>55&&l<235){let weight=Math.abs(l-125)+10;sx+=x*weight;sy+=y*weight;n+=weight}}if(!n)return;let pos={x:sx/n/w,y:sy/n/h,t:Date.now()};if(!lastPos||Math.hypot(pos.x-lastPos.x,pos.y-lastPos.y)>.018){data.movement.push(pos);lastPos=pos;playerDot.style.left=`${pos.x*100}%`;playerDot.style.top=`${pos.y*100}%`;update()}}catch(e){}}
async function endSession(){if(rally)endRally();tracking=false;clearInterval(timer);stopVision();await stopRecording();let duration=Date.now()-sessionStart,total=data.shots,rs=data.rallies,longest=Math.max(0,...rs.map(r=>r.shots)),avg=rs.length?(total/rs.length).toFixed(1):"0",record={date:new Date().toISOString(),rallies:rs.length,shots:total,avg,longest,movement:data.movement.length,duration};let hist=JSON.parse(localStorage.getItem("svSessions")||"[]");hist.unshift(record);localStorage.setItem("svSessions",JSON.stringify(hist.slice(0,20)));sumRallies.textContent=record.rallies;sumShots.textContent=total;sumAvg.textContent=avg;sumLongest.textContent=longest;sumMovement.textContent=record.movement;sumSessionTime.textContent=fmt(duration);summaryDate.textContent=new Date().toLocaleString();drawHeatmap();stopCamera();show("summary");renderHistory()}
function drawHeatmap(){let c=heatCanvas,x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle="#b8ff5a";x.globalAlpha=.55;x.lineWidth=2;x.strokeRect(28,20,w-56,h-40);x.beginPath();x.moveTo(28,h/2);x.lineTo(w-28,h/2);x.stroke();x.globalAlpha=.14;for(let p of data.movement){x.beginPath();x.arc(28+p.x*(w-56),20+p.y*(h-40),18,0,Math.PI*2);x.fillStyle="#b8ff5a";x.fill()}x.globalAlpha=1}
function renderHistory(){let hist=JSON.parse(localStorage.getItem("svSessions")||"[]");recentList.innerHTML=hist.length?hist.slice(0,5).map(x=>`<div class="recent-item"><div><strong>${new Date(x.date).toLocaleDateString()}</strong><small>${x.rallies} rallies · ${x.movement||0} movement samples</small></div><span>${x.shots}<small> shots</small></span></div>`).join(""):`<div class="empty">No sessions yet. Your first Match Vision session will appear here.</div>`}
openTracker.onclick=async()=>{show("tracker");await startCamera();setUI()};backBtn.onclick=async()=>{if(tracking&&!confirm("End this recording and go back?"))return;if(tracking){tracking=false;clearInterval(timer);stopVision();await stopRecording()}stopCamera();show("home")};flipBtn.onclick=async()=>{if(tracking)return alert("End the recording before switching cameras.");facing=facing==="environment"?"user":"environment";await startCamera()};sessionBtn.onclick=()=>tracking?endSession():beginSession();rallyBtn.onclick=toggleRally;shotBtn.onclick=addShot;saveVideoBtn.onclick=saveVideo;visionToggle.onchange=()=>visionToggle.checked?startVision():stopVision();newSession.onclick=async()=>{videoCard.classList.add("hidden");show("tracker");await startCamera();setUI()};homeBtn.onclick=()=>show("home");historyBtn.onclick=()=>document.querySelector(".recent").scrollIntoView({behavior:"smooth"});clearHistory.onclick=()=>{if(confirm("Clear session history on this device?")){localStorage.removeItem("svSessions");renderHistory()}};renderHistory();