document.addEventListener('DOMContentLoaded',function(){
const $=s=>document.querySelector(s),screens=['home','tracker','summary'];
const E={camera:$('#camera'),cameraFallback:$('#cameraFallback'),visionStatus:$('#visionStatus'),visionCanvas:$('#visionCanvas'),playerDot:$('#playerDot'),rallies:$('#rallies'),shots:$('#shots'),movement:$('#movement'),sessionBtn:$('#sessionBtn'),shotBtn:$('#shotBtn'),rallyBtn:$('#rallyBtn'),statusPill:$('#statusPill'),rallyLive:$('#rallyLive'),liveTime:$('#liveTime'),recPill:$('#recPill'),recTime:$('#recTime'),visionToggle:$('#visionToggle'),savedVideo:$('#savedVideo'),videoCard:$('#videoCard'),videoNote:$('#videoNote'),saveVideoBtn:$('#saveVideoBtn'),sumRallies:$('#sumRallies'),sumShots:$('#sumShots'),sumAvg:$('#sumAvg'),sumLongest:$('#sumLongest'),sumMovement:$('#sumMovement'),sumSessionTime:$('#sumSessionTime'),summaryDate:$('#summaryDate'),heatCanvas:$('#heatCanvas'),recentList:$('#recentList')};
let stream=null,facing='environment',tracking=false,rally=false,sessionStart=0,rallyStart=0,timer=null,mediaRecorder=null,chunks=[],videoBlob=null,visionTimer=null,lastPos=null,recording=false,data={rallies:[],shots:0,movement:[]};
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));window.scrollTo(0,0)}
function fmt(ms,d){let s=Math.max(0,ms)/1000,m=Math.floor(s/60),r=s%60;return m+':'+(d?r.toFixed(1).padStart(4,'0'):Math.floor(r).toString().padStart(2,'0'))}
async function startCamera(){stopCamera();E.visionStatus.textContent='Opening camera…';if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia){E.visionStatus.textContent='Camera not supported in this browser';return false}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}},audio:true})}catch(err){try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing}},audio:false})}catch(err2){E.cameraFallback.style.display='grid';E.visionStatus.textContent='Camera unavailable · check permission';return false}}E.camera.srcObject=stream;try{await E.camera.play()}catch(err){}E.cameraFallback.style.display='none';E.visionStatus.textContent=stream.getAudioTracks().length?'Camera + microphone ready':'Camera ready · no audio';return true}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}if(E.camera)E.camera.srcObject=null}
function startRecording(){chunks=[];videoBlob=null;recording=false;if(!stream||typeof MediaRecorder==='undefined'){E.visionStatus.textContent='Tracking active · recording not supported';return false}try{let opts;for(const type of ['video/mp4','video/webm;codecs=vp8,opus','video/webm']){try{if(MediaRecorder.isTypeSupported(type)){opts={mimeType:type};break}}catch(e){}}mediaRecorder=new MediaRecorder(stream,opts);mediaRecorder.ondataavailable=e=>{if(e.data&&e.data.size>0)chunks.push(e.data)};mediaRecorder.onstop=()=>{if(!chunks.length)return;videoBlob=new Blob(chunks,{type:mediaRecorder.mimeType||'video/mp4'});E.savedVideo.src=URL.createObjectURL(videoBlob);E.videoCard.classList.remove('hidden');E.videoNote.textContent=(videoBlob.size/1048576).toFixed(1)+' MB · ready to save';E.saveVideoBtn.textContent='Save video'};mediaRecorder.onerror=()=>{recording=false;E.recPill.classList.add('hidden')};mediaRecorder.start(1000);recording=true;return true}catch(err){console.error('Recorder:',err);E.visionStatus.textContent='Tracking active · recorder unavailable';return false}}
function stopRecording(){return new Promise(resolve=>{if(mediaRecorder&&mediaRecorder.state!=='inactive'){mediaRecorder.addEventListener('stop',resolve,{once:true});try{mediaRecorder.stop()}catch(e){resolve()}}else resolve()})}
function update(){E.rallies.textContent=data.rallies.length;E.shots.textContent=data.shots;E.movement.textContent=data.movement.length}
function setUI(){E.sessionBtn.textContent=tracking?'End & Save Session':'Start & Record';E.sessionBtn.dataset.active=tracking?'1':'0';E.shotBtn.disabled=!tracking||!rally;E.rallyBtn.disabled=!tracking;E.rallyBtn.textContent=rally?'End rally':'Start rally';E.statusPill.textContent=tracking?'TRACKING':'READY';E.statusPill.className='status '+(tracking?'live':'idle');E.rallyLive.classList.toggle('hidden',!rally);E.recPill.classList.toggle('hidden',!tracking||!recording)}
function beginSession(){/* UI changes first so the tap always gives feedback */tracking=true;sessionStart=Date.now();data={rallies:[],shots:0,currentShots:0,movement:[]};lastPos=null;update();setUI();E.visionStatus.textContent='Starting tracking…';recording=startRecording();startVision();setUI();clearInterval(timer);timer=setInterval(()=>{if(rally)E.liveTime.textContent=fmt(Date.now()-rallyStart,true);if(tracking)E.recTime.textContent=fmt(Date.now()-sessionStart,false)},100)}
function toggleRally(){if(!tracking)return;if(!rally){rally=true;rallyStart=Date.now();data.currentShots=0}else endRally();update();setUI()}
function endRally(){if(!rally)return;data.rallies.push({shots:data.currentShots||0,duration:Date.now()-rallyStart});rally=false;data.currentShots=0}
function addShot(){if(!rally)return;data.currentShots++;data.shots++;if(navigator.vibrate)navigator.vibrate(18);update()}
function startVision(){clearInterval(visionTimer);if(!E.visionToggle.checked){E.visionStatus.textContent=recording?'Recording · vision off':'Tracking · vision off';return}E.visionStatus.textContent=recording?'Tracking + recording':'Tracking active';visionTimer=setInterval(sampleMovement,500)}
function stopVision(){clearInterval(visionTimer);visionTimer=null;E.visionStatus.textContent='Vision paused'}
function sampleMovement(){if(!tracking||!E.visionToggle.checked||E.camera.readyState<2)return;let c=E.visionCanvas,ctx=c.getContext('2d',{willReadFrequently:true}),w=96,h=128;c.width=w;c.height=h;try{ctx.drawImage(E.camera,0,0,w,h);let p=ctx.getImageData(0,0,w,h).data,sx=0,sy=0,n=0;for(let y=8;y<h;y+=4)for(let x=4;x<w;x+=4){let i=(y*w+x)*4,l=(p[i]+p[i+1]+p[i+2])/3;if(l>55&&l<235){let wt=Math.abs(l-125)+10;sx+=x*wt;sy+=y*wt;n+=wt}}if(!n)return;let pos={x:sx/n/w,y:sy/n/h,t:Date.now()};if(!lastPos||Math.hypot(pos.x-lastPos.x,pos.y-lastPos.y)>.018){data.movement.push(pos);lastPos=pos;E.playerDot.style.left=(pos.x*100)+'%';E.playerDot.style.top=(pos.y*100)+'%';update()}}catch(e){}}
async function endSession(){if(rally)endRally();tracking=false;clearInterval(timer);stopVision();await stopRecording();recording=false;let duration=Date.now()-sessionStart,total=data.shots,rs=data.rallies,longest=Math.max(0,...rs.map(r=>r.shots)),avg=rs.length?(total/rs.length).toFixed(1):'0',record={date:new Date().toISOString(),rallies:rs.length,shots:total,avg:avg,longest:longest,movement:data.movement.length,duration:duration};let hist=JSON.parse(localStorage.getItem('svSessions')||'[]');hist.unshift(record);localStorage.setItem('svSessions',JSON.stringify(hist.slice(0,20)));E.sumRallies.textContent=record.rallies;E.sumShots.textContent=total;E.sumAvg.textContent=avg;E.sumLongest.textContent=longest;E.sumMovement.textContent=record.movement;E.sumSessionTime.textContent=fmt(duration,false);E.summaryDate.textContent=new Date().toLocaleString();drawHeatmap();stopCamera();show('summary');renderHistory()}
function drawHeatmap(){let c=E.heatCanvas,x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='#b8ff5a';x.globalAlpha=.55;x.lineWidth=2;x.strokeRect(28,20,w-56,h-40);x.beginPath();x.moveTo(28,h/2);x.lineTo(w-28,h/2);x.stroke();x.globalAlpha=.14;data.movement.forEach(p=>{x.beginPath();x.arc(28+p.x*(w-56),20+p.y*(h-40),18,0,Math.PI*2);x.fillStyle='#b8ff5a';x.fill()});x.globalAlpha=1}
function saveVideo(){if(!videoBlob)return;let ext=videoBlob.type.indexOf('webm')>=0?'webm':'mp4',url=URL.createObjectURL(videoBlob),a=document.createElement('a');a.href=url;a.download='ShuttleVision-'+Date.now()+'.'+ext;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),3000);E.saveVideoBtn.textContent='Video saved ✓'}
function renderHistory(){let hist=JSON.parse(localStorage.getItem('svSessions')||'[]');E.recentList.innerHTML=hist.length?hist.slice(0,5).map(x=>'<div class="recent-item"><div><strong>'+new Date(x.date).toLocaleDateString()+'</strong><small>'+x.rallies+' rallies · '+(x.movement||0)+' movement samples</small></div><span>'+x.shots+'<small> shots</small></span></div>').join(''):'<div class="empty">No sessions yet. Your first Match Vision session will appear here.</div>'}
$('#openTracker').addEventListener('click',async()=>{show('tracker');await startCamera();setUI()});
E.sessionBtn.addEventListener('click',function(e){e.preventDefault();if(tracking){endSession()}else{beginSession()}});
E.rallyBtn.addEventListener('click',toggleRally);E.shotBtn.addEventListener('click',addShot);E.saveVideoBtn.addEventListener('click',saveVideo);
$('#backBtn').addEventListener('click',async()=>{if(tracking&&!confirm('End this recording and go back?'))return;if(tracking){tracking=false;clearInterval(timer);stopVision();await stopRecording()}stopCamera();show('home')});
$('#flipBtn').addEventListener('click',async()=>{if(tracking){alert('End the session before switching cameras.');return}facing=facing==='environment'?'user':'environment';await startCamera()});
E.visionToggle.addEventListener('change',()=>{if(!tracking)return;E.visionToggle.checked?startVision():stopVision()});
$('#newSession').addEventListener('click',async()=>{E.videoCard.classList.add('hidden');show('tracker');await startCamera();setUI()});$('#homeBtn').addEventListener('click',()=>show('home'));$('#historyBtn').addEventListener('click',()=>document.querySelector('.recent').scrollIntoView({behavior:'smooth'}));$('#clearHistory').addEventListener('click',()=>{if(confirm('Clear session history on this device?')){localStorage.removeItem('svSessions');renderHistory()}});renderHistory();setUI();
});