const $=s=>document.querySelector(s);const screens=["home","tracker","summary"];let stream=null,facing="environment",tracking=false,rally=false,sessionStart=0,rallyStart=0,timer=null,data={rallies:[],shots:0};
function show(id){screens.forEach(x=>$("#"+x).classList.toggle("active",x===id));window.scrollTo(0,0)}
function fmt(ms,decimal=false){let s=Math.max(0,ms)/1000,m=Math.floor(s/60),r=s%60;return `${m}:${decimal?r.toFixed(1).padStart(4,"0"):Math.floor(r).toString().padStart(2,"0")}`}
async function startCamera(){stopCamera();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}},audio:false});$("#camera").srcObject=stream;$("#cameraFallback").style.display="none"}catch(e){$("#cameraFallback").style.display="grid"}}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function update(){$("#rallies").textContent=data.rallies.length;$("#shots").textContent=data.shots;$("#currentShots").textContent=rally?data.currentShots||0:0}
function setTrackingUI(){$("#sessionBtn").textContent=tracking?"End session":"Start tracking";$("#shotBtn").disabled=!tracking||!rally;$("#rallyBtn").disabled=!tracking;$("#rallyBtn").textContent=rally?"End rally":"Start rally";$("#statusPill").textContent=tracking?"TRACKING":"READY";$("#statusPill").className="status "+(tracking?"live":"idle");$("#rallyLive").classList.toggle("hidden",!rally)}
function beginSession(){tracking=true;sessionStart=Date.now();data={rallies:[],shots:0,currentShots:0};update();setTrackingUI();timer=setInterval(()=>{if(rally)$("#liveTime").textContent=fmt(Date.now()-rallyStart,true)},100)}
function toggleRally(){if(!tracking)return;if(!rally){rally=true;rallyStart=Date.now();data.currentShots=0}else{endRally()}update();setTrackingUI()}
function endRally(){if(!rally)return;data.rallies.push({shots:data.currentShots||0,duration:Date.now()-rallyStart});rally=false;data.currentShots=0}
function addShot(){if(!rally)return;data.currentShots++;data.shots++;if(navigator.vibrate)navigator.vibrate(18);update()}
function endSession(){if(rally)endRally();tracking=false;clearInterval(timer);const duration=Date.now()-sessionStart;const total=data.shots,rs=data.rallies,longest=Math.max(0,...rs.map(r=>r.shots)),play=rs.reduce((a,r)=>a+r.duration,0),avg=rs.length?(total/rs.length).toFixed(1):"0";const record={date:new Date().toISOString(),rallies:rs.length,shots:total,avg,longest,play,duration};let hist=JSON.parse(localStorage.getItem("svSessions")||"[]");hist.unshift(record);localStorage.setItem("svSessions",JSON.stringify(hist.slice(0,20)));$("#sumRallies").textContent=record.rallies;$("#sumShots").textContent=total;$("#sumAvg").textContent=avg;$("#sumLongest").textContent=longest;$("#sumPlayTime").textContent=fmt(play);$("#sumSessionTime").textContent=fmt(duration);$("#summaryDate").textContent=new Date().toLocaleString();stopCamera();show("summary");renderHistory()}
function renderHistory(){const el=$("#recentList"),hist=JSON.parse(localStorage.getItem("svSessions")||"[]");el.innerHTML=hist.length?hist.slice(0,5).map(x=>`<div class="recent-item"><div><strong>${new Date(x.date).toLocaleDateString()}</strong><small>${x.rallies} rallies · ${fmt(x.duration)}</small></div><span>${x.shots}<small> shots</small></span></div>`).join(""):`<div class="empty">No sessions yet. Your first training summary will appear here.</div>`}
$("#openTracker").onclick=async()=>{show("tracker");await startCamera();setTrackingUI()};$("#backBtn").onclick=()=>{if(tracking&&!confirm("End this session and go back?"))return;if(tracking){clearInterval(timer);tracking=false;rally=false}stopCamera();show("home")};$("#flipBtn").onclick=async()=>{facing=facing==="environment"?"user":"environment";await startCamera()};$("#sessionBtn").onclick=()=>tracking?endSession():beginSession();$("#rallyBtn").onclick=toggleRally;$("#shotBtn").onclick=addShot;$("#newSession").onclick=async()=>{show("tracker");await startCamera();setTrackingUI()};$("#homeBtn").onclick=()=>show("home");$("#historyBtn").onclick=()=>$(".recent").scrollIntoView({behavior:"smooth"});$("#clearHistory").onclick=()=>{if(confirm("Clear session history on this device?")){localStorage.removeItem("svSessions");renderHistory()}};document.addEventListener("visibilitychange",()=>{if(document.hidden&&stream)stream.getVideoTracks().forEach(t=>t.enabled=false);else if(stream)stream.getVideoTracks().forEach(t=>t.enabled=true)});renderHistory();